### ISSUE TITLE
Inconsistencies in how sub-pixel values are rounded

### ISSUE THREAD

**Issue by evantbyrne** [Fyrd/caniuse#1616]
A decent overview on the issue on sub-pixel rounding: http://ejohn.org/blog/sub-pixel-problems-in-css/

Figured it's worth adding a short note of some kind to the "Known Issues" tab on the [CSS calc page](http://caniuse.com/#feat=calc), since using division/percentages with calc can yield a variety of results. E.g., a row of three columns styled as so:

```css
.col {
  margin-right: 20px;
  width: calc((100% - 40px) / 3);
}
.col:last-child {
  margin-right: 0;
}
```

will overflow at certain widths in IE 9+.

Forgive me if I'm not going about this correctly!
