### ISSUE TITLE
`:placeholder-shown` partially supported in Chrome 47

### ISSUE THREAD

**Issue by hail2u** [Fyrd/caniuse#2150]
Chrome 47 doesn’t support `color` property (used in Can I use... test case) in `:placeholder-shown` pseudo class, but support `font-weight` property.

Test case: https://jsfiddle.net/gg6smqqd/1/

Also we can debug in developer tools:

![cap-20151216-124705](https://cloud.githubusercontent.com/assets/68940/11831616/2b6afde8-a3f3-11e5-95b1-6064302f2515.png)

**Comment by yisibl** [comment]
Is `:placeholder-shown`.

**Comment by yisibl** [comment]
This is not a bug.

Because it is not to define the style of placeholder, it is used to match an element when placeholder is displayed(shown).

You can used this:

```css
::-webkit-input-placeholder {
  color: inherit; /* Or currentcolor */
}
```

Or 

```css
:placeholder-shown::-webkit-input-placeholder {
  color: red;
}
```
