### ISSUE TITLE
top-center等和@page相关的内容

### ISSUE THREAD

**Issue by likyh** [Fyrd/caniuse#4034]
top-center等和@page相关的内容
https://drafts.csswg.org/css-page-3/#at-page-rule

**Comment by Fyrd** [comment]
I believe this refers to "Page-margin boxes" , defined at https://drafts.csswg.org/css-page-3/#margin-boxes

Support for other paged media properties is already on the site at https://caniuse.com/#feat=css-paged-media

**Comment by likyh** [comment]
no no no, i think Page-margin boxes not only @page, and i need @top-center and so.

**Comment by edgar444** [comment]
Chrome *does* support `@page`, like
``` css
@page {
  margin: 5cm;
}
```
but *does not* support "Page-margin boxes", like
``` css
@page {
  @top-center {
    content: "4422";
    background-color: red;
    border: black 5px solid;
    width: 5cm;
    height: 5cm;
  }
}
```
Played around in practice by trying to print pdf from chrome 67. And I failed. There is software like weasyprint that did produce the red boxes. Anyway, It's a nice detail to advertise.
