### ISSUE TITLE
Add Individual Transform Properties

### ISSUE THREAD

**Issue by vfonic** [Fyrd/caniuse#4159]
I stumbled upon this part of the spec draft and was wondering what's the browser support for it:
https://drafts.csswg.org/css-transforms-2/#individual-transforms

Basically it adds three new CSS properties:

```css
<selector> {
  translate: 15px 20px;
  scale: 0.5;
  rotate: 90deg;
}
```

As opposed to specifying everything in `transform` property:

```css
<selector> {
  transform: translate(15px 20px) scale(0.5) rotate(90deg);
}
```

I couldn't find any reference to it on caniuse website.

Is it there and I just can't find it?
