### ISSUE TITLE
Add `text-edge` and `leading-trim`

### ISSUE THREAD

**Issue by sergeysova** [Fyrd/caniuse#5571]
```css
h1 { 
 text-edge: cap alphabetic;
 leading-trim: both;
}
```

https://medium.com/microsoft-design/leading-trim-the-future-of-digital-typesetting-d082d84b202

- https://www.w3.org/TR/2020/WD-css-inline-3-20200618/#propdef-leading-trim
- https://www.w3.org/TR/2020/WD-css-inline-3-20200618/#propdef-text-edge
