### ISSUE TITLE
webkit-calendar-picker-indicator

### ISSUE THREAD

**Issue by dcyou** [Fyrd/caniuse#5658]
this pseudo element is not defined

**Comment by dcyou** [comment]
I suggest also to add those:
- webkit-datetime-edit-year-field
- webkit-datetime-edit-month-field
- webkit-datetime-edit-day-field

**Comment by dcyou** [comment]
https://jsfiddle.net/y8fbcvL6/1/

**Comment by huksley** [comment]
Would be great to have this added!
Since Firefox >= 109 there is visual issue that you can't hide date picker icon, i.e. following is not working anymore:

```css
input[type="date"]::-webkit-calendar-picker-indicator {
    background: none;
}
```

So browser compatibility transparency is important!
