### ISSUE TITLE
Add tech() function support (in @font-face src)

### ISSUE THREAD

**Issue by Schweinepriester** [Fyrd/caniuse#6436]
- Spec: https://www.w3.org/TR/css-fonts-4/#font-tech-definitions
- Chrome:
  - Intend to ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/_9k-Ne8FRu4/m/Y5t_T50pAgAJ
  - https://chromestatus.com/feature/5088679224147968
  - Shipping in Chrome 107
- Firefox:
  - https://github.com/mozilla/standards-positions/issues/563
  - https://bugzilla.mozilla.org/show_bug.cgi?id=1715546
  - Seemingly shipping in Firefox 105

[Example from the spec](https://www.w3.org/TR/css-fonts-4/#example-e9f3647f):
```css
@font-face {
    font-family: "Trickster";
    src: url("trickster-COLRv1.otf") format(opentype) tech(color-COLRv1), /* ← here */
         url("trickster-outline.otf") format(opentype);
}
```
