### ISSUE TITLE
@viewport media query?

### ISSUE THREAD

**Issue by cheapsteak** [Fyrd/caniuse#644]
Just saw this on reddit  
http://www.reddit.com/r/Frontend/comments/2bdqhz/about_the_viewport/  

Supposedly Microsoft requires this

``` css
@-ms-viewport {
  width: device-width;
}
```

A treehouse article on this:  
http://blog.teamtreehouse.com/thinking-ahead-css-device-adaptation-with-viewport  

>  Currently, support for `@viewport` is limited to Opera and IE10. It seems like Chrome (and hopefully others) will be implementing it soon, though, as it’s expected to replace the viewport meta tag as the official web standard in the near future.  

``` css
@-ms-viewport {
   width: device-width;
}
@-o-viewport { 
   width: device-width;
}
@viewport {
   width: device-width; 
}
```
