### ISSUE TITLE
IE11 doesn't support angle units in `hsl()`

### ISSUE THREAD

**Issue by Goodwine** [Fyrd/caniuse#6614]
IE11 doesn't support `<angle>` units in `hsl()`. I recently noticed that the following snippet would not work for IE11:

```css
.box {
  height: 50px;
  background: hsl(200deg, 100%, 50%); /* fails because of "deg" units */
}
```

However, it does work when removing the units:
```css
.box {
  height: 50px;
  background: hsl(200, 100%, 50%); /* works */
}
```

FWIW - `<angle>` does work in IE11, for example `transform: rotate(45deg);` works fine.
The problem is only in `hsl(<angle>, ...)`
