### ISSUE TITLE
Design: Content in Feature Panel too wide

### ISSUE THREAD

**Issue by kelunik** [Fyrd/caniuse#813]
Feature panel can be too wide: [screenshot](http://i.imgur.com/ITeywI9.png) / [live](http://caniuse.com/#search=websocket)

This can be fixed using the following CSS:

``` css
.feature-panel-container .num-note {
    margin: 0.5em 0px 0px;
    width: -moz-max-content;
    max-width: -moz-available; /* <-- add this line */
}
```
